# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-ios-arlen-pereira' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios-arlen-pereira
  pod 'Alamofire', '4.9.1'
  pod 'SDWebImage', '5.4.0'
  pod 'RxSwift', '5.0.1'
  pod 'RxCocoa', '5.0.1'
  pod 'JGProgressHUD', '2.1'
  pod 'MMBannerLayout', '5.0.7'
  pod 'CryptoSwift', '1.3.0'
  pod 'CollectionViewSlantedLayout', '3.1.1'

  target 'desafio-ios-arlen-pereiraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-ios-arlen-pereiraUITests' do
    # Pods for testing
  end

end
